[package]
name = "chess-engine"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "benchmark"
path = "src/bin/benchmark.rs"

[dependencies]
regex = "1"
log = "0.4"
env_logger = "0.11"
ratatui = "0.29"
crossterm = "0.29"
rustyline = "16.0"
